import axios from 'axios';

import { PaginatedBody } from 'echadospalante-domain/dist/app/modules/domain/common/pagination';

import env from '../../../../../../environment/environment';
import { ApiResponse } from '../../domain/api';
import { Quote } from '../../domain/quote';

export class QuotesApi {
  private static readonly API_BASE_URL = `${env.API_URL}/api/v1/cotizaciones`;

  public static async fetchQuotes(
    page: number,
    size: number,
  ): Promise<PaginatedBody<Quote>> {
    return axios
      .get<ApiResponse<PaginatedBody<Quote>>>(
        `${QuotesApi.API_BASE_URL}?pagina=${page}&cantidad=${size}`,
        //{ withCredentials: true }
      )
      .then(({ data }) => data.message);

    /*
    const response: PaginatedBody<Quote> = {
      items: [
        {
          id: "1",
          codigo: "DS20240822-3AC01EF0",
          cliente: {
            id: "1",
            nombres: "Pepito",
            apellidos: "Alvarez",
            email: "pepito.alvarez@gmail.com",
            codigoPais: 57,
            telefono: "3122555475",
            empresa: {
              id: "1",
              nit: "123456789",
              nombre: "Empresa Prueba 1",
              verificada: false,
              fechaCreacion: "2024-08-01",
            },
            verificado: false,
            fechaCreacion: "2024-08-13",
          },
          asesor: {
            id: 1,
            firstName: "Pepita",
            lastName: "Pereza",
            identification: "1234",
            phoneCode: 57,
            phoneNumber: "3001234567",
            createdAt: "2024-08-23",
            updatedAt: "2024-08-23",
          },
          area: {
            id: 1,
            name: "Analítica de Datos",
            quotes: null,
            createdAt: null,
          },
          estado: "ACTIVA",
          formulario: "",
          etapas: [],
          fechaCreacion: "2024-08-13T00:00:00",
          fechaActualizacion: "2024-08-19T00:00:00",
        },
        // {
        //   id: 2,
        //   code: "234",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 3,
        //   code: "345",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.NOT_COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 4,
        //   code: "456",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.NOT_COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 5,
        //   code: "567",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 3,
        //     name: "Digitalizacion de Formularios",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 6,
        //   code: "678",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 3,
        //     name: "Digitalizacion de Formularios",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 7,
        //   code: "789",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 8,
        //   code: "890",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 9,
        //   code: "098",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 10,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.NOT_COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 11,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 12,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 13,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 1,
        //   code: "123",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 2,
        //   code: "234",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 3,
        //   code: "345",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 4,
        //   code: "456",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 5,
        //   code: "567",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 3,
        //     name: "Digitalizacion de Formularios",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 6,
        //   code: "678",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 3,
        //     name: "Digitalizacion de Formularios",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 7,
        //   code: "789",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.NOT_COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 8,
        //   code: "890",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 9,
        //   code: "098",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 10,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 11,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 12,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.NOT_COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 13,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 1,
        //   code: "123",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 2,
        //   code: "234",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 3,
        //   code: "345",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.NOT_COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 4,
        //   code: "456",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 5,
        //   code: "567",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 3,
        //     name: "Digitalizacion de Formularios",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 6,
        //   code: "678",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 3,
        //     name: "Digitalizacion de Formularios",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 7,
        //   code: "789",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.NOT_COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 8,
        //   code: "890",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 9,
        //   code: "098",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 1,
        //     name: "Desarrollo de Software",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 10,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 11,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 12,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.ACTIVE,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
        // {
        //   id: 13,
        //   code: "987",
        //   date: new Date(),
        //   name: "Some project name",
        //   area: {
        //     id: 2,
        //     name: "Diseño UI/UX",
        //     createdAt: new Date(),
        //   },
        //   advisor: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     createdAt: new Date(),
        //   },
        //   state: VentureState.NOT_COMPLETED,
        //   client: {
        //     id: 1,
        //     firstName: "John",
        //     lastName: "Doe",
        //     email: "jondoe@gmail.com",
        //     phoneCode: "57",
        //     phoneNumber: "123456789",
        //     company: {
        //       id: 1,
        //       nit: "123456789",
        //       name: "Company",
        //       createdAt: new Date(),
        //     },
        //     createdAt: new Date(),
        //   },
        // },
      ],
      total: 39,
    };

    return Promise.resolve(response);

    */
  }

  public static async deleteQuote(id: string): Promise<void> {
    // return axios.delete(`${QuotesApi.API_BASE_URL}/non-standards/${id}`);
    console.log({ id });
    return Promise.resolve();
  }

  public static async fetchQuoteDetail(id: string): Promise<Quote> {
    console.log({ id });
    // return axios
    //   .get<Quote>(`${QuotesApi.API_BASE_URL}/${id}`)
    //   .then(({ data }) => data);
    throw new Error('Method not implemented.');
  }
}
